### ISSUE TITLE
Switch to a faster result data serialization format

### ISSUE THREAD

**Issue by ojdo** [tum-ens/urbs#47]
### The problem

The current choice of using Pickle for saving and loading the state of an optimization problem instance was made due to coding convenience, not of performance. For large instances (full year, ten sites, ten processes, about 20 connections, 1 storage technology) saving or loading a problem instance including solution using pickle-based `urbs.save` (or `urbs.load`) takes longer than the solver needs to find the solution.
### The reason

Pyomo. Really, Pyomo creates a Python object for every single variable/parameter/constraint for each time step/technology/... combination that exists. These operations also make the problem creation process rather slow.
### The solution

Instead of saving `prob` (a Pyomo "ConcreteModel" object) with millions of descendent objects, a several DataFrames could be saved to a HDF file. Important: this dump must include _all_ information that one could want to retrieve now or later, as it will replace the giant _scenario_x.pgz_ file that is now written by `urbs.save` after each scenario has been optimized by the solver.
### Possibly superseded by

If the model itself is no longer created by Pyomo, but by, let's say, [JuMP](https://jump.readthedocs.org/), saving the result/optimal state might be possible differently. However, as such a move is not properly investigated yet to draw such a conclusion, this feature might be very valuable.
### To-do list (draft)
- [x] Inventory of information to store. (Rough idea: result of functions `get_constants` and `get_timeseries` for all _demand_ (only? or also all "intermediate") commodities in all sites)
- [x] Investigate serialization format (HDF, Pickle, Flat file, all of them)
- [x] Implement store/retrieve functions
- [x] Deprecate old save/load functions or improve them (semi-)transparently

**Comment by ojdo** [comment]
## Inventory
Kind of obvious (in hindsight): simply call `get_entity` once for each model entity returned by a call to `list_entities` for each of the entity types *set*, *parameter*, *variable*, *objective*, *constraint*. Using this, no manual maintenance is required and all possibly interesting information is preserved.

## Serialization format
Pandas [supports HDF5](http://pandas.pydata.org/pandas-docs/stable/io.html#hdf5-pytables) by relying on the PyTables package.

## Internal result representation
A (possibly nested) dictionary of pandas Series:

    result = {
        'set': { 't': <Series>, 'tm': <Series>, 'com': <Series>, ... },
        'par': { 'w': <Series>, ... },
        'var': { ... },
        'obj': { ... },
        'con': { ... }}

Alternative: a nested `AttrDict` for easier access like `result.var.e_pro_out`.

## Further thoughts
The choice of representation has ripple effects concerning functions `get_timeseries` and `get_constants`, which should switch to relying on the result representation that gets automatically updated by a solver run. This in turn calls for creating a custom class (`urbs`, maybe?) that bundles this new behaviour. Then, an urbs object could either be created in its solved state by reading input + solving, or by directly loading a HDFStore file, populating the internal result data structure. Additional meta information (time stamps, scenario descriptions, notes) could transparently be added.

**Comment by ojdo** [comment]
Update on internal result representation: the dictionary probably should not be nested by entity type, to make the logic of function `get_entity` simpler, like:

```python
def get_entity(instance, name):
    if name in instance._results:
        return instance._results[name]
    else:
        raise SomeException
```

The hidden `_result` field should get populated automatically after a successful solver run. Perhaps, the output of `list_entities` (entity name, type and domain) could be stored where?
